name: Self-hosted test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: dev1
    steps:
      - name: Print runner info
        run: |
          #Write-Host "Runner is working"
          #Get-ComputerInfo | Select-Object WindowsVersion, OsName, OsArchitecture
          echo "Runner is working"
          uname -a
